### ISSUE TITLE
Hard Coded Lead Information

### ISSUE THREAD

**Issue by jdomian** [monkishtypist/avala-api-gforms-feed#1]
In the README.md you say the plugin is not supported by Avala and to "Use this" plugin for anyone that needs it. 

Just be aware, in your arrays for Lead Sources, Categories and Types, these are hard-coded into your script (avala-api-gforms-feed.php). Every Aimbase client has different Lead Sources, Categories and Types. Unless these are changed per client, they will error the lead out when trying to post to our API.

We may create a plugin for WordPress in 2017, but these dropdown control values will be dynamically generated based on APIs in Aimbase. We currently have plugins for other CMS platforms, but nothing for Apache based CMS tools.

**Comment by monkishtypist** [comment]
removed the hard-coded references and added a settings field for adding custom field mappings. this should now be more generic usage, and available for customization for each new project.
